### ISSUE TITLE
Rails 5 issue

### ISSUE THREAD

**Issue by alejandrodevs** [FortAwesome/font-awesome-sass#114] opened 2016-02-25 05:33 UTC
I'm getting this when I start rails server (rails5.0.0.beta3):

`undefined method 'start_with?' for /font-awesome\/fontawesome-webfont\.(?:eot|svg|ttf|woff|woff2?)$/:Regexp`

**Comment by maartenvanvliet** [comment] 2016-03-25 14:43
Caused by this issue: https://github.com/rails/sprockets-rails/issues/269

Sprockets no longer accepts regexes

**Comment by kugaevsky** [comment] 2016-04-20 21:22
@alejandrodevs you can use my PR to fix it.

**Comment by supercodepoet** [comment] 2016-05-04 14:17
Should be fixed in the latest 4.6.1 just pushed

**Closed by supercodepoet** 2016-05-04 14:17 UTC
